### ISSUE TITLE
argument names and types

### ISSUE THREAD

**Issue by ggrothendieck** [MatHatter/olr_r#1]
The first argument is `datasetname` but if it were a name it would be a character string. In fact it is the data itself, not its name.  It should be called just `data`.

Also `resvarname` is difficult to understand and should be `responseName`.  Similarly `expvarnames` should be `predictorNames` .

Finally the way `lm` works is that `lm(data)` without any other arguments assumes that the first column is the response vector and the remaining  columns are the predictors and it would be userful if these defaults were used in `olr` as well.   If the response variable is specified and the predictor variables are not then they should default to be all columns except the response variable.

In the help page for `olr` it states that `expnames` is a list but from the example it seems that it is not a list but a character vector.

**Comment by MatHatter** [comment]
Hello,
Thank you for your advice, I will make the appropriate changes. Good point about the data, the variable names make more sense, as I was thinking about clarifying those. I will look more into the default arguments of lm(). That is indeed a vector, yet I think we just called it a list in college, so I will change that.
Thanks,
Mathew
 

 
  On Tue, Dec 24, 2019 at 11:14 AM, ggrothendieck<notifications@github.com> wrote:   
The first argument is datasetname but if it were a name it would be a character string. In fact it is the data itself, not its name. It should be called just data.

Also resvarname is difficult to understand and should be responseName. Similarly expvarnames should be predictorNames .

Finally the way lm works is that lm(data) without any other arguments assumes that the first column is the response vector and the remaining columns are the predictors and it would be userful if these defaults were used in olr as well. If the response variable is specified and the predictor variables are not then they should default to be all columns except that specified in resvarname.

In the help page for olr it states that expnames is a list but from the example it seems that it is not a list but a character vector.

**Comment by MatHatter** [comment]
I will be uploading the revision soon. I actually completed all the lm() default stuff tonight. I will double check everything tomorrow before I send it in again. 

for the `datasetname`, I changed it to`dataset`, because `data` was already used in my source code and I didn't want to mess it up potentially or potentially call a keyword.

Thanks!
